name: Report bundle size

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
jobs:
  file_size_impact:
    runs-on: ubuntu-latest

    steps:
      - name: Setup git
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16.13.0"
      - run: yarn install
      - name: Report changes
        run: node ./tools/size-reporter.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
